### ISSUE TITLE
Symfony example doc does not work without the weird error in onKernelTerminate

### ISSUE THREAD

**Issue by rbaarsma** [B-Galati/monolog-sentry-handler#15]
I've fully followed this guide: https://github.com/B-Galati/monolog-sentry-handler/blob/1.2.0/doc/guide-symfony.md

At first I tried without the buffering, and I got a log in sentry, but it was called `app.ERROR: 500 returned`, instead of the actual exception message.

This turned out to be this line:
```
        if ($statusCode >= 500) {
            // 5XX response are private/security data safe so let's log them for debugging purpose
            $this->logger->error('500 returned', ['response' => $event->getResponse()]);
        }
```

I removed this line, as I did not really see any point to it and turned on buffering. 

But then sentry seemed to receive nothing anymore. 

After an hour more of debugging (and getting frustrated with the lack of output after the `register_shutdown_function` I finally came to this solution

```
public function onKernelTerminate(TerminateEvent $event): void
{
   // ... 

   $this->logger->reset();
}
```

Now it works as expected. 

I'm not sure if this is a bug in monolog (BufferHandler) or the combination of the BufferHandler and the HttpClient both using register_shutdown_function (??)

But I thought I might at least share my experience. See if anybody else ran into similar problems and if there's better solutions.

**Comment by rbaarsma** [comment]
Perhaps it's because it's late, but on env=prod (in my production environment). It's not working at all

```
monolog:
    handlers:
        # Capture errors through "fingers_crossed", which triggers only on level error or higher, but buffers context.
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            buffer_size: 50
            excluded_http_codes: [401, 403, 404, 412, 422, 503]
            stop_buffering: true

        # fingers_crossed triggers both stream writing as a buffered sentry log
        grouped:
            type: group
            members:
                - streamed
                - sentry_buffer

        # Stream log to pod output.
        streamed:
            type: stream
            path: "php://stdout"
            level: info

        # send sentry logs buffered
        sentry_buffer:
            type: buffer
            handler: sentry_handler
        sentry_handler:
            type: service
            id: BGalati\MonologSentryHandler\SentryHandler
```
