### ISSUE TITLE
404 exception are still logged in sentry

### ISSUE THREAD

**Issue by allan-simon** [B-Galati/monolog-sentry-handler#24]
I'm using symfony5.2  and version 1.2.2 of this bundle 

my monolog.yaml looks like this 

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        sentry:
            type: fingers_crossed
            action_level: warning
            handler: sentry_buffer
            excluded_http_codes: [400, 401, 403, 404, 405]
            buffer_size: 100 # Prevents memory leaks for workers
            channels: ["!event", "!security"]
        sentry_buffer:
            type: buffer
            handler: sentry_handler
        sentry_handler:
            type: service
            id: 'BGalati\MonologSentryHandler\SentryHandler'
```

however despite the `excluded_http_codes`  i still see the 40X errors sentry

I discovered this while trying to add `exclude_404s`  https://symfony.com/doc/current/logging/monolog_regex_based_excludes.html  to only filters out some 404 ,  i discovered that actually with the current configuration I should have any in the first place
